baseURL = 'http://192.168.100.66:1313'
title = 'larissaldr'
languageCode = 'en-us'
# timeZone = "Brazil"
# theme = "ldr-hugo-theme"

[params]
    author = "Larissa Dantas Requena"
    info = "Full stack developer, UI Design, Arts and other things"
    description = "My name is Larissa Dantas Requena, full stack software engineer"
    keywords = "larissa dantas requena, larissa, dantas, requena"

[[params.social]]
    name = "Email"
    weight = 1
    url = "/contact"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/lari-ldr"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/larissarequena/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/blog/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"