baseURL = 'http://localhost:1313'
title = 'larissaldr'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
[taxonomies]
  category = "categories"
  tag = "tags"
[params]
    author = "Larissa Dantas Requena"
    info = "Full stack developer, UI Design, Arts and other things"
    description = "My name is Larissa Dantas Requena, full stack software engineer"
    warning = "All content on this blog is handwritten. No AI-generated content is used."
    keywords = "larissa dantas requena, larissa, dantas, requena"
    notFoundTitle = "Page Not Found"
    notFoundDescription = "This page does not exist."
    notFoundGoHome = "Go to homepage"
[[params.social]]
    name = "Email"
    weight = 1
    url = "/contact"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/lari-ldr"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/larissarequena/"
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/blog/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"